version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-fintelligence}
    ports:
      - ${POSTGRES_PORT:-5432}:5432 # For exposing, we'll still be using 5432 inside of docker.
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      DOCKER: 'true'
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} # postgres -> container's host, 5432 -> postgres' port inside container
    ports:
      - ${DOCKER_API_PORT-3001}:3001
    depends_on:
      - postgres
      - redis

  vueapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DOCKER: 'true'
    ports:
      - ${DOCKER_APP_PORT:-80}:80
    depends_on:
      - server

volumes:
  postgres_data:
